<script setup lang="ts">
import { computed, type Component } from 'vue'
import {
  PhArrowClockwise,
  PhArrowCounterClockwise,
  PhArrowDown,
  PhArrowUp,
  PhDotsSixVertical,
  PhFloppyDisk,
  PhListChecks,
  PhGitBranch,
  PhArrowElbowDownRight,
  PhUploadSimple,
  PhArrowsClockwise,
  PhArrowsDownUp,
  PhBrain,
  PhCaretDown,
  PhCaretLeft,
  PhCaretRight,
  PhCaretUp,
  PhChartBar,
  PhChatCircle,
  PhCheck,
  PhClockCountdown,
  PhCheckCircle,
  PhInfo,
  PhCloud,
  PhCheckSquare,
  PhLockSimple,
  PhXCircle,
  PhCircleNotch,
  PhCopy,
  PhCube,
  PhDotsThree,
  PhEye,
  PhEyeSlash,
  PhFile,
  PhFileText,
  PhMapTrifold,
  PhMicrophone,
  PhFolder,
  PhGauge,
  PhHardDrives,
  PhGear,
  PhGlobe,
  PhGraphicsCard,
  PhImage,
  PhMagnifyingGlass,
  PhMegaphoneSimple,
  PhMoon,
  PhPaperclip,
  PhPause,
  PhDownloadSimple,
  PhArrowSquareOut,
  PhFastForward,
  PhRewind,
  PhSpeakerHigh,
  PhSpeakerSlash,
  PhPaperPlaneTilt,
  PhPencilSimple,
  PhPlay,
  PhPlug,
  PhPlus,
  PhPulse,
  PhPushPin,
  PhScroll,
  PhShield,
  PhMinus,
  PhMinusSquare,
  PhSidebarSimple,
  PhSlidersHorizontal,
  PhSquare,
  PhStack,
  PhStop,
  PhSun,
  PhTable,
  PhTerminalWindow,
  PhThermometerSimple,
  PhTrash,
  PhWarning,
  PhWebcam,
  PhWrench,
  PhX,
} from '@phosphor-icons/vue'

// App icon `name` -> Phosphor (regular weight) component. Call sites keep the
// stable `<Icon name="...">` API; the lucide->phosphor swap lives entirely here.
// The Truespar logo in ActivityBar is bespoke inline SVG and stays as-is.
const MAP: Record<string, Component> = {
  send: PhPaperPlaneTilt,
  stop: PhStop,
  copy: PhCopy,
  check: PhCheck,
  'check-circle': PhCheckCircle,
  info: PhInfo,
  lock: PhLockSimple,
  'x-circle': PhXCircle,
  regenerate: PhArrowsClockwise,
  trash: PhTrash,
  plus: PhPlus,
  search: PhMagnifyingGlass,
  x: PhX,
  'chevron-left': PhCaretLeft,
  'chevron-right': PhCaretRight,
  'chevron-down': PhCaretDown,
  'chevron-up': PhCaretUp,
  'message-square': PhChatCircle,
  box: PhCube,
  settings: PhGear,
  sliders: PhSlidersHorizontal,
  sun: PhSun,
  moon: PhMoon,
  brain: PhBrain,
  edit: PhPencilSimple,
  'panel-left': PhSidebarSimple,
  paperclip: PhPaperclip,
  image: PhImage,
  'arrow-down': PhArrowDown,
  'arrow-up': PhArrowUp,
  // Reads: a fixed list of questions, each answered - the checklist glyph.
  'list-checks': PhListChecks,
  table: PhTable,
  'git-branch': PhGitBranch,
  'corner-down-right': PhArrowElbowDownRight,
  // the grab handle on a reorderable row (six dots, the platform idiom)
  'drag-handle': PhDotsSixVertical,
  upload: PhUploadSimple,
  save: PhFloppyDisk,
  'rotate-left': PhArrowCounterClockwise,
  'rotate-right': PhArrowClockwise,
  spinner: PhCircleNotch,
  'more-horizontal': PhDotsThree,
  file: PhFile,
  'alert-triangle': PhWarning,
  plug: PhPlug,
  wrench: PhWrench,
  terminal: PhTerminalWindow,
  globe: PhGlobe,
  cloud: PhCloud,
  shield: PhShield,
  square: PhSquare,
  'check-square': PhCheckSquare,
  minus: PhMinus,
  'minus-square': PhMinusSquare,
  pin: PhPushPin,
  'arrow-up-down': PhArrowsDownUp,
  'file-text': PhFileText,
  map: PhMapTrifold,
  microphone: PhMicrophone,
  clock: PhClockCountdown,
  folder: PhFolder,
  'hard-drive': PhHardDrives,
  gauge: PhGauge,
  'chart-bar': PhChartBar,
  thermometer: PhThermometerSimple,
  'graphics-card': PhGraphicsCard,
  eye: PhEye,
  'eye-off': PhEyeSlash,
  server: PhStack,
  activity: PhPulse,
  play: PhPlay,
  pause: PhPause,
  webcam: PhWebcam,
  rewind: PhRewind,
  'fast-forward': PhFastForward,
  volume: PhSpeakerHigh,
  'volume-off': PhSpeakerSlash,
  download: PhDownloadSimple,
  'external-link': PhArrowSquareOut,
  scroll: PhScroll,
  // Feedback. Deliberately not the chat bubble: `message-square` already means
  // "the Studio" in the area toggle two controls away, and two glyphs meaning
  // different things is worse than one extra import.
  megaphone: PhMegaphoneSimple,
}

const props = defineProps<{ name: string; size?: number }>()
const cmp = computed<Component | null>(() => MAP[props.name] ?? null)
const dim = computed(() => props.size ?? 18)
</script>

<template>
  <!-- class/style/aria fall through to Phosphor's <svg> root, so existing
       `.foo svg {}` rules and inline :style opacity toggles keep working. -->
  <component :is="cmp" v-if="cmp" :size="dim" weight="regular" />
</template>
